version: '2'
services:
  web:
    image: appsol/laravel-docker:apache-5.6
    container_name: laravel-docker_web
    domainname: laravel-docker.dev
    hostname: laravel-docker
    ports:
      - 80:80
    tty: true
    volumes:
      - ./public_html:/var/www/html
    links:
      - db:mysql
    depends_on:
      - db
    env_file: .env
  db:
    image: mariadb:latest
    container_name: laravel-docker_db
    ports:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d/
      - ./data/conf/:/etc/mysql/conf.d
    env_file: .env
