version: '3'
services:
  web:
    image: nginx:latest
    container_name: php-docker_web
    domainname: php-docker.test
    hostname: php-docker
    ports:
      - 80:80
      - 443:443
    tty: true
    volumes:
      - ./public_html:/var/www/html
      - ./conf/nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    image: php-docker:7.2-fpm
    container_name: php-docker_app
    ports:
      - 9000
    volumes:
      - ./public_html:/var/www/html
    working_dir: /var/www/html
    links:
      - db:mysql
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: php-docker_db
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d/
      - ./data/conf/:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php-docker
      - MYSQL_USER=php-docker_user
      - MYSQL_PASSWORD=php-docker_pass
  cache:
    container_name: php-docker_cache
    image: redis:alpine
    ports:
      - 6379
    restart: on-failure
  mail:
    image: schickling/mailcatcher
    container_name: php-docker_mail
    ports:
      - 1080:1080
    restart: on-failure