version: '2'
services:
  web:
    build: .
    image: laravel-docker:apache-7.1
    ports:
      - 80:80
    tty: true
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=laraveldocker.dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldocker
      - DB_DATABASE=laraveldocker
      - MYSQL_USER=laraveldocker_user
      - DB_USERNAME=laraveldocker_user
      - MYSQL_PASSWORD=laraveldocker_pass
      - DB_PASSWORD=laraveldocker_pass
      - LARAVEL=blog
      - DOCUMENTROOT=blog/public

  db:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldocker
      - MYSQL_USER=laraveldocker_user
      - MYSQL_PASSWORD=laraveldocker_pass
