version: '2'
services:
  web:
    build: .
    image: laravel-docker:apache-5.6
    # container_name: laravel-docker_web
    # domainname: laravel-docker.dev
    # hostname: laravel-docker
    ports:
      - 80:80
    # volumes:
    #   - ./public_html:/var/www/html
    tty: true
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      - DEV_NAME=laraveldocker
      - DEV_DOMAIN=laraveldocker.dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldocker
      - DB_DATABASE=laraveldocker
      - MYSQL_USER=laraveldocker_user
      - DB_USERNAME=laraveldocker_user
      - MYSQL_PASSWORD=laraveldocker_pass
      - DB_PASSWORD=laraveldocker_pass
      - PATH=$PATH:/root/.composer/vendor/bin/
      - LARAVEL=blog

    # restart: on-failure
  db:
    image: mariadb:latest
    # container_name: laravel-docker_db
    ports:
      - 3306
    # volumes:
    #   - ./data/db:/var/lib/mysql
    #   - ./data/import:/docker-entrypoint-initdb.d/
    #   - ./data/conf/:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laraveldocker
      - MYSQL_USER=laraveldocker_user
      - MYSQL_PASSWORD=laraveldocker_pass
    # restart: on-failure
